// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxukKL5swuhD8vrHA_kq5sKFq2bfyzOIE',
    appId: '1:202710802753:web:47cc2fa7da0f76239601c0',
    messagingSenderId: '202710802753',
    projectId: 'chatify-with-firebase-35eb1',
    authDomain: 'chatify-with-firebase-35eb1.firebaseapp.com',
    storageBucket: 'chatify-with-firebase-35eb1.appspot.com',
    measurementId: 'G-CWEMT9047Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2IWZRmtQyh8rsk1Txi2cm7W30ZIisBpE',
    appId: '1:202710802753:android:91d59db245579c299601c0',
    messagingSenderId: '202710802753',
    projectId: 'chatify-with-firebase-35eb1',
    storageBucket: 'chatify-with-firebase-35eb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD6qeTXsNzXxAwmkMAQ9VuViRTtzQiFWc',
    appId: '1:202710802753:ios:1a284af9a93f8e079601c0',
    messagingSenderId: '202710802753',
    projectId: 'chatify-with-firebase-35eb1',
    storageBucket: 'chatify-with-firebase-35eb1.appspot.com',
    iosBundleId: 'com.example.chatifyWithFirebase',
  );
}
